dataset:
  name: cifar100
  root: /home/cn0025/datasets/cifar100/ciFAIR-100
  num_classes: 100
  noise_rate: 0.7
  train_files:
    - ${dataset.root}/synthetic_experts_2/train_0_1_2_3_4_5_6_7_8_9_10_11_12_13_14_${dataset.noise_rate}_3.json
    - ${dataset.root}/synthetic_experts_2/train_0_1_2_3_4_5_6_7_8_9_10_11_12_13_14_${dataset.noise_rate}_4.json
    - ${dataset.root}/synthetic_experts_2/train_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_${dataset.noise_rate}_13.json
    - ${dataset.root}/synthetic_experts_2/train_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_${dataset.noise_rate}_14.json
  train_ground_truth_file: ${dataset.root}/train.json
  test_files:
    - ${dataset.root}/synthetic_experts_2/test_0_1_2_3_4_5_6_7_8_9_10_11_12_13_14_${dataset.noise_rate}_3.json
    - ${dataset.root}/synthetic_experts_2/test_0_1_2_3_4_5_6_7_8_9_10_11_12_13_14_${dataset.noise_rate}_4.json
    - ${dataset.root}/synthetic_experts_2/test_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_${dataset.noise_rate}_13.json
    - ${dataset.root}/synthetic_experts_2/test_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_${dataset.noise_rate}_14.json
  test_ground_truth_file: ${dataset.root}/test.json

model:
  _partial_: True
  _target_: models.PreActResNet.ResNet18

training:
  lr: 0.01
  batch_size: 128
  num_epochs: 100
  clipped_norm: 10
  seed: 44
  num_samples: null

hparams:
  resize: null
  crop_size: [32, 32]
  mean: null
  std: null
  epsilon_lower: [0., 0., 0., 0., 0.]
  epsilon_upper: [0.2, 0.2, 0.2, 0.2, 0.2]