dataset:
  name: MiceBone
  root: /sda2/datasets/MiceBone
  num_classes: 3
  train_files:
    - ${dataset.root}/split_folds/Id_47_not_fold5.json
    - ${dataset.root}/split_folds/Id_290_not_fold5.json
    - ${dataset.root}/split_folds/Id_533_not_fold5.json
    - ${dataset.root}/split_folds/Id_534_not_fold5.json
    - ${dataset.root}/split_folds/Id_580_not_fold5.json
    - ${dataset.root}/split_folds/Id_581_not_fold5.json
    - ${dataset.root}/split_folds/Id_745_not_fold5.json
    - ${dataset.root}/split_folds/Id_966_not_fold5.json
  train_ground_truth_file: ${dataset.root}/split_folds/majority_vote_not_fold5.json
  test_files:
    - ${dataset.root}/split_folds/Id_47_fold5.json
    - ${dataset.root}/split_folds/Id_290_fold5.json
    - ${dataset.root}/split_folds/Id_533_fold5.json
    - ${dataset.root}/split_folds/Id_534_fold5.json
    - ${dataset.root}/split_folds/Id_580_fold5.json
    - ${dataset.root}/split_folds/Id_581_fold5.json
    - ${dataset.root}/split_folds/Id_745_fold5.json
    - ${dataset.root}/split_folds/Id_966_fold5.json
  test_ground_truth_file: ${dataset.root}/split_folds/majority_vote_fold5.json

model:
  _partial_: True
  _target_: models.ResNet.ResNet18
  in_channels: 3  # color images: 3, black and white: 1
  conv1_kernel_size: [7, 7]

training:
  lr: 0.0025
  batch_size: 64
  num_epochs: 300
  clipped_norm: null
  num_samples: null

hparams:
  resize: null
  crop_size: [224, 224]
  mean: null
  std: null
  num_eval_samples: null
  epsilon_lower: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
  epsilon_upper: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2]